- name: Restart wg-quick
  ansible.builtin.systemd:
    name: "wg-quick@{{ my_wireguard_client_wg_interface }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Apply sysctl now
  ansible.builtin.command: sysctl --system
  changed_when: false
