# ── General ──────────────────────────────────────────────────────────────
my_named_mode: [] # master or slave
my_named_base_dir: /var/cache/bind
my_named_log_dir: /var/log/named
my_named_zone_dir: "{{ my_named_base_dir }}"
my_named_bind_user: bind
my_named_enable_ipv6: true

# ── Settings ─────────────────────────────────────────────────────────────
my_named_master_ip: [] # need to be setup on slaves
my_named_zones: [] # e.g. ['example.com', '1.168.192.in-addr.arpa']
my_named_forwarders:
  - 1.1.1.1
  - 8.8.8.8
my_named_querys_allowed_by: []
my_named_transfers_allowed_by: []
my_named_resolv_conf_search_domain: "{{ local_fqdn }}"
my_named_resolv_conf_nameservers:
  - 192.168.1.53
my_named_manage_resolv_conf: true

# ── Logging ──────────────────────────────────────────────────────────────
my_named_logging_channels:
  - name: default_file
    file: "{{ my_named_log_dir }}/default.log"
  - name: general_file
    file: "{{ my_named_log_dir }}/general.log"
  - name: database_file
    file: "{{ my_named_log_dir }}/database.log"
  - name: security_file
    file: "{{ my_named_log_dir }}/security.log"
  - name: config_file
    file: "{{ my_named_log_dir }}/config.log"
  - name: resolver_file
    file: "{{ my_named_log_dir }}/resolver.log"
  - name: xfer-in_file
    file: "{{ my_named_log_dir }}/xfer-in.log"
  - name: xfer-out_file
    file: "{{ my_named_log_dir }}/xfer-out.log"
  - name: notify_file
    file: "{{ my_named_log_dir }}/notify.log"
  - name: client_file
    file: "{{ my_named_log_dir }}/client.log"
  - name: unmatched_file
    file: "{{ my_named_log_dir }}/unmatched.log"
  - name: queries_file
    file: "{{ my_named_log_dir }}/queries.log"
  - name: network_file
    file: "{{ my_named_log_dir }}/network.log"
  - name: update_file
    file: "{{ my_named_log_dir }}/update.log"
  - name: dispatch_file
    file: "{{ my_named_log_dir }}/dispatch.log"
  - name: dnssec_file
    file: "{{ my_named_log_dir }}/dnssec.log"
  - name: lame-servers_file
    file: "{{ my_named_log_dir }}/lame-servers.log"

my_named_logging_categories:
  - name: default
    channels: [default_file]
  - name: general
    channels: [general_file]
  - name: database
    channels: [database_file]
  - name: security
    channels: [security_file]
  - name: config
    channels: [config_file]
  - name: resolver
    channels: [resolver_file]
  - name: xfer-in
    channels: [xfer-in_file]
  - name: xfer-out
    channels: [xfer-out_file]
  - name: notify
    channels: [notify_file]
  - name: client
    channels: [client_file]
  - name: unmatched
    channels: [unmatched_file]
  - name: queries
    channels: [queries_file]
  - name: network
    channels: [network_file]
  - name: update
    channels: [update_file]
  - name: dispatch
    channels: [dispatch_file]
  - name: dnssec
    channels: [dnssec_file]
  - name: lame-servers
    channels: [lame-servers_file]

# define this host_vars or group_vars
# my_named_zones:
#   - example.local

# my_named_zone_definitions:
#   - name: example.local
#     file: db.example.local
#     ttl: 86400
#     soa:
#       mname: ns1.example.local.
#       rname: hostmaster.example.local.
#       serial: 2025051005
#     ns:
#       - ns1.example.local.
#       - ns2.example.local.
#     records:
#       - { name: "@", type: A, value: 192.168.2.10 }
#       - { name: ns1, type: A, value: 192.168.2.11 }
#       - { name: ns2, type: A, value: 192.168.2.12 }
#       - { name: test, type: A, value: 192.168.2.13 }
