- name: "Import ip-forwarding.yml"
  ansible.builtin.import_tasks: ip-forwarding.yml

- name: Ensure packages present (WireGuard + tools)
  ansible.builtin.package:
    name:
      - wireguard
      - wireguard-tools
    state: present

- name: Render /etc/wireguard/*.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{ my_wireguard_client_wg_interface }}.conf"
    owner: root
    group: root
    mode: "0600"
  notify: Restart wg-quick

- name: Enable and start wg-quick@{{ my_wireguard_client_wg_interface }}
  ansible.builtin.systemd:
    name: "wg-quick@{{ my_wireguard_client_wg_interface }}"
    enabled: true
    state: started
