- name: Copy check_pihole.sh to /usr/local/bin
  ansible.builtin.copy:
    src: files/check_pihole.sh
    dest: /usr/local/bin/check_pihole.sh
    owner: root
    group: root
    mode: "0755"
  tags:
    - role-my.pihole
    - check_pihole

- name: Enable nonlocal IP binding for keepalived
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_nonlocal_bind = 1
      net.ipv6.ip_nonlocal_bind = 1
  notify: Reload sysctl config

- name: Force install keepalived package
  ansible.builtin.apt:
    force_apt_get: true
    name: keepalived

- name: Configure keepalived
  ansible.builtin.template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.j2
    mode: "0644"
  notify: Restart keepalived
