- name: Reload bind
  ansible.builtin.command: rndc reload
  notify: Restart bind # fall back to full restart if rndc fails
  failed_when: false

- name: Restart bind
  ansible.builtin.service:
    name: named
    state: restarted

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 300
