# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#tip-for-variables-and-vaults

# dhcpcd.conf
vault_my_essentials_network_static_ip_1:
vault_my_essentials_network_gateway:
vault_my_essentials_network_domain_name: "{{ vault_local_fqdn }}" # group_vars/all/vault.yml
vault_my_essentials_network_domain_search: "{{ vault_local_fqdn }}" # group_vars/all/vault.yml
vault_my_essentials_network_dns_1:

# Role: my.wireguard-client
vault_my_wireguard_client_wg_private_key:
vault_my_wireguard_client_public_key:
vault_my_wireguard_client_preshared_key:
vault_my_wireguard_client_endpoint:

# Role: my.tailscale
vault_my_tailscale_auth_key:
