# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#tip-for-variables-and-vaults

# Pi-hole
vault_pihole_webpassword:

# Network Configuration
vault_my_essentials_network_static_ip_1:
vault_my_essentials_network_static_ip_2:
vault_my_essentials_network_gateway:
vault_my_essentials_network_domain_name: "{{ vault_local_fqdn }}"
vault_my_essentials_network_domain_search: "{{ vault_local_fqdn }}"
vault_my_essentials_network_dns_1:
vault_my_essentials_network_dns_2:
