# Ansible Setup
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
ansible_port: "{{ vault_ansible_port }}"
ansible_ssh_private_key_file: "{{ vault_ansible_ssh_private_key_file }}"

# Role: my.tailscale
my_tailscale_auth_key: "{{ vault_my_tailscale_auth_key }}"
my_tailscale_advertise_routes: ["192.168.1.0/24", "10.4.0.0/24"]
my_tailscale_advertise_exit_node: true
my_tailscale_extra_flags: ["--accept-dns=false"]
