# - name: "Role: my.essentails - npm-install.yml - npm-install"
#   become: true
#   become_user: root
#   community.general.npm:
#     name: "{{ my_essentials_npm_packages }}"
#     state: present

- name: Ensure node and npm are installed
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes
  become: true
  when: my_essentials_install_node | default(true)
